#include<bits/stdc++.h>
using namespace std;
int main()
{
	//To compare if the files are same, we read from both the files simultaneously and check if there is any mistmatch. We convert the character to integer(Implicit typecasting) in order to avoid any errors due to mismatch of the type of content read from the files.
	ifstream file1("SelfGeneratedBinary.txt");
	ifstream file2("MarsGeneratedBinary.txt");
	string str1,str2;
	int num1,num2;
	do
	{
		getline(file1,str1);
		getline(file2,str2);
		for(int i=0;i<32;i++)
		{
			num1=str1[i];
			num2=str2[i];
			if(num1!=num2)
			{
				cout << "The output generated by the self-written assembler doesn't match the output generated by MARS" << endl;
				return 0;
			}
		}
	}while(file1.eof()==0 && file2.eof()==0);
	file1.close();
	file2.close();
	cout << "The output generated by self-written assembler matches the output generated by MARS" << endl;
	return 0;
}
